### PR TITLE
Create github actions

### PR DESCRIPTION
**Pull request by goens**
For now it's just testing in Linux, could extend to add osx/windows

### CODE REVIEW

**Comment by goens** [comment]
Note that CI fails because of the missing `nauty/` directory (it can't build). This should be resolved when #2 is merged.

**Comment by pdobsan** [comment]
Moving tests under the umbrella of [pytest](https://docs.pytest.org/en/stable/) is __a very good idea__! Even if they at the moment test the same functionalities as the old ones, `pytest` make it easier to add new ones not just for us but also for our users.

I have already tried them by cherry picking only the `pytest` related commits into a local branch.
They worked nicely, ... well kind of. More precisely they work in `~/.local` (or global) install but fail in a `virtualenv`. This latter case, it seems, is a long time problem with `pytest`, the internet full of related questions, complaints and various "solutions". There was also a warning about `tests_require = ...` being  unknown option in `setup.py`.

We need to get `tests` working during `build` without any install, in a `~/.local` install or in a `virtualenv`. And of course, testing should be in the Makefile's control on the top level. I don't mind if `make` calls `setup.py` under the hood, it already does in other cases.

Having no experience with Github actions (yet) I cannot really comment on them. One thing perhaps, creating separate *github action* branches for `building`, `testing`, `install` phases might be a good idea.

For any case, I suppose you need to adapt them to the changes introduced by merge 3c315fb0beb920985b14edc0ae68e7583bfe37d2.

**Comment by goens** [comment]
Thanks! 

The virtualenv issue is really strange. It also works with my manual virtualenv, but I cannot reproduce it on a clean installation.

Why do you think separating the github actions in different branches would make sense? Isn't the idea to merge them all into master anyway? Or do you mean have different actions that test the different parts? I can look into that, but I guess it would require creating a fresh environment every time, so we'd be building three times (once for build, once for install and once for test).

I'll close this PR and make a new one from my fork.

**Comment by pdobsan** [comment]
Oops, I missed this comment, but you read my mind see my other comment. You are right, no need for these branches.

Anyway, could we go without github actions *for the time being* and focus only on `pytest` integration in my pedestrian way, as my other comment. Testing has (should have) nothing to do with install.

**Pull request closed without merging**
