### PR TITLE
Added canon_label for finding canonical labelings

### PR DESCRIPTION
**Pull request by sammorley-short**
@pdobsan: There's probably some extra stuff I should add here, but I was having trouble getting the testsuite to run as expected. While I debug that, here's the (WIP) PR.

### CODE REVIEW

**Comment by sammorley-short** [comment]
@pdobsan: Local install now working, so can run tests now. Current version is passing, although test suite for `isomorphic` looks like it's just testing isomorphism between copied graphs, rather than two isomorphic graphs with different vertex labels.

The easiest way to properly test `isomorphic` and `canon_label` would be to implement the `Graph.relabel` method that would take a relabelling list and apply it to the graph in-place. Is this something that you would interested in adding? Once that is applied then testing for isomorphism is as simple as supplying a series of random relabelings and checking for isomorphism. Similarly, for `canon_label`, a if you take two identical graphs, relabel one, find both graphs' canonical relabelings, then applying those relabelings should yield the same graph in both cases.

Let me know if this would be something you're interested in. Thanks!

**Comment by sammorley-short** [comment]
Also, I don't seem to have the access to link them, but this PR would close #15.

**Comment by pdobsan** [comment]
@sammorley-short: Thanks for this, I have just merged it into main and loading the new version up to PyPi.

> The easiest way to properly test isomorphic and canon_label would be to implement the Graph.relabel method that would take a relabelling list and apply it to the graph in-place.
> ...
> Let me know if this would be something you're interested in

Yes you are right, that would be a nice improvement.

**Comment by pdobsan** [comment]
Opened issue #17 on relabeling, created a branch [relabeling](/pdobsan/pynauty/tree/relabeling) and pushed an initial implementation of the `relabel(g,xs)` procedure.

**Pull request merged**
